name: Build and Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/django-app:latest .

      # Push the Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/django-app:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   # Deploy to Digital Ocean Droplet
  #   - name: Deploy to Digital Ocean
  #     uses: appleboy/ssh-action@v0.1.6
  #     with:
  #       host: ${{ secrets.DROPLET_IP }}
  #       username: ${{ secrets.DROPLET_USER }}
  #       key: ${{ secrets.DROPLET_SSH_KEY }}
  #       port: ${{ secrets.DROPLET_SSH_PORT }}
  #       script: |
  #         docker pull ${{ secrets.DOCKER_USERNAME }}/django-app:latest
  #         docker stop django-app || true
  #         docker rm django-app || true
  #         docker run -d --name django-app -p 80:8000 ${{ secrets.DOCKER_USERNAME }}/django-app:latest
