name: Upload Test Results Artifact on PR

on:
  pull_request:
    branches:
      - main # The target branch for the PR

jobs:
  check-tests:
    name: Check Test Results
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests and generate coverage report
        run: |
          pytest --maxfail=1 --disable-warnings -q
          pytest --cov=project > result.log

      - name: Upload test result as artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-results-${{ github.head_ref }}
          path: result.log
